[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Steelux"
version = "0.1.0"
description = "SteelSeries Software for Linux!"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyusb>=1.2.1",
]

[project.scripts]
mytool = "main:main"

[tool.setuptools.packages.find]
where = ["src"]